import Link from 'next/link';
import ThemeToggle from '@/components/ThemeToggle';
const data={
 es:{nav:['Inicio','Sobre mí','Proyectos','Servicios','Blog','Contacto'],tag:'Tecnología e innovación',title:'Transformo ideas en soluciones digitales.',intro:'Soy Isaías Díaz. Comparto mis proyectos y desarrollo soluciones web, aplicaciones y automatizaciones con inteligencia artificial.',projects:'Proyectos destacados',projectsDesc:'Herramientas y plataformas que he desarrollado.',services:'Servicios digitales',servicesDesc:'Soluciones prácticas para personas, marcas y negocios.',about:'Sobre mí',aboutText:'Me apasiona crear herramientas útiles y explorar nuevas posibilidades de la tecnología.',blog:'Blog',blogText:'Próximamente compartiré artículos sobre tecnología, inteligencia artificial y desarrollo digital.',contact:'Hablemos de tu proyecto',contactText:'¿Tienes una idea o propuesta de colaboración? Escríbeme para conversar.',cta:'Ver proyectos',contactCta:'Contactar',theme:'Cambiar tema',cards:['Desarrollo web','Aplicaciones digitales','Automatización con IA'],descs:['Sitios modernos, rápidos y adaptables.','Herramientas prácticas para web y escritorio.','Flujos que ayudan a ahorrar tiempo y esfuerzo.'],visit:'Visitar proyecto'},
 en:{nav:['Home','About','Projects','Services','Blog','Contact'],tag:'Technology and innovation',title:'Turning ideas into digital solutions.',intro:'I am Isaías Díaz. I share my projects and build websites, applications and AI-powered automations.',projects:'Featured projects',projectsDesc:'Tools and platforms I have developed.',services:'Digital services',servicesDesc:'Practical solutions for people, brands and businesses.',about:'About me',aboutText:'I enjoy creating useful tools and exploring new possibilities with technology.',blog:'Blog',blogText:'Articles about technology, artificial intelligence and digital development are coming soon.',contact:'Let’s talk about your project',contactText:'Have an idea or a collaboration proposal? Get in touch.',cta:'View projects',contactCta:'Contact',theme:'Toggle theme',cards:['Web development','Digital applications','AI automation'],descs:['Modern, fast and responsive websites.','Useful web and desktop tools.','Workflows that save time and effort.'],visit:'Visit project'},
 pt:{nav:['Início','Sobre mim','Projetos','Serviços','Blog','Contato'],tag:'Tecnologia e inovação',title:'Transformo ideias em soluções digitais.',intro:'Sou Isaías Díaz. Compartilho meus projetos e desenvolvo sites, aplicativos e automações com inteligência artificial.',projects:'Projetos em destaque',projectsDesc:'Ferramentas e plataformas que desenvolvi.',services:'Serviços digitais',servicesDesc:'Soluções práticas para pessoas, marcas e empresas.',about:'Sobre mim',aboutText:'Gosto de criar ferramentas úteis e explorar novas possibilidades com tecnologia.',blog:'Blog',blogText:'Em breve, artigos sobre tecnologia, inteligência artificial e desenvolvimento digital.',contact:'Vamos conversar sobre seu projeto',contactText:'Tem uma ideia ou proposta de colaboração? Entre em contato.',cta:'Ver projetos',contactCta:'Contato',theme:'Alternar tema',cards:['Desenvolvimento web','Aplicativos digitais','Automação com IA'],descs:['Sites modernos, rápidos e responsivos.','Ferramentas úteis para web e desktop.','Fluxos que economizam tempo e esforço.'],visit:'Visitar projeto'}
} as const;
type Lang=keyof typeof data;
export function generateStaticParams(){return [{lang:'es'},{lang:'en'},{lang:'pt'}]}
export default async function Page({params}:{params:Promise<{lang:string}>}){
 const {lang}=await params;const locale:Lang=lang==='en'||lang==='pt'?lang:'es';const t=data[locale];
 return <><header className="top wrap"><Link className="brand" href={`/${locale}/`}>Isaías Díaz</Link><nav className="nav" aria-label="Main navigation">{t.nav.map((x,i)=><a key={x} href={`#${['home','about','projects','services','blog','contact'][i]}`}>{x}</a>)}</nav><div className="langs">{(['es','en','pt'] as const).map(x=><Link key={x} href={`/${x}/`} aria-current={locale===x?'page':undefined}>{x.toUpperCase()}</Link>)}<ThemeToggle label={t.theme}/></div></header>
 <main><section className="hero wrap" id="home"><div className="eyebrow">{t.tag}</div><h1>{t.title}</h1><p>{t.intro}</p><div className="actions"><a className="btn primary" href="#projects">{t.cta}</a><a className="btn" href="#contact">{t.contactCta}</a></div></section>
 <section className="section wrap" id="about"><h2>{t.about}</h2><p className="lead">{t.aboutText}</p></section>
 <section className="section wrap" id="projects"><h2>{t.projects}</h2><p className="lead">{t.projectsDesc}</p><div className="grid"><article className="card"><h3>UtiliToolsPro</h3><p>Online tools and digital utilities.</p><a href="https://utilitoolspro.com/" target="_blank" rel="noopener noreferrer">{t.visit} ↗</a></article><article className="card"><h3>Radio Juvenil</h3><p>Radio digital y música urbana cristiana.</p><a href="https://radiojuvenil24h.blogspot.com/" target="_blank" rel="noopener noreferrer">{t.visit} ↗</a></article><article className="card"><h3>UtiliZip</h3><p>Desktop file compression utility. </p></article></div></section>
 <section className="section wrap" id="services"><h2>{t.services}</h2><p className="lead">{t.servicesDesc}</p><div className="grid">{t.cards.map((c,i)=><article className="card" key={c}><h3>{c}</h3><p>{t.descs[i]}</p></article>)}</div></section>
 <section className="section wrap" id="blog"><h2>{t.blog}</h2><p className="lead">{t.blogText}</p></section>
 <section className="section wrap" id="contact"><h2>{t.contact}</h2><p className="lead">{t.contactText}</p></section></main><footer className="footer"><div className="wrap">© {new Date().getFullYear()} Isaías Díaz · {t.tag}</div></footer></>;
}
