import type { Metadata } from 'next';
import Link from 'next/link';
import ThemeToggle from '@/components/ThemeToggle';
import ContactForm from '@/components/ContactForm';
const data={
 es:{nav:['Inicio','Sobre mí','Proyectos','Servicios','Blog','Contacto'],tag:'Tecnología e innovación',title:'Transformamos ideas en soluciones digitales.',intro:'Somos un proyecto digital impulsado por Isaías Díaz. Creamos soluciones web, aplicaciones y automatizaciones con inteligencia artificial para personas y negocios.',projects:'Proyectos destacados',projectsDesc:'Herramientas y plataformas que he desarrollado.',services:'Servicios digitales',servicesDesc:'Creamos soluciones prácticas para personas, marcas y negocios.',about:'Sobre mí',aboutText:'Me apasiona crear herramientas útiles y explorar nuevas posibilidades de la tecnología.',blog:'Blog',blogText:'Próximamente compartiré artículos sobre tecnología, inteligencia artificial y desarrollo digital.',contact:'Hablemos de tu proyecto',contactText:'¿Tienes una idea o propuesta de colaboración? Escríbeme para conversar.',cta:'Ver proyectos',contactCta:'Contactar',theme:'Cambiar tema',cards:['Desarrollo web','Aplicaciones digitales','Automatización con IA'],descs:['Páginas corporativas y sitios profesionales adaptados a móviles, con rendimiento y SEO técnico.','Herramientas a medida para simplificar tareas y procesos de negocio.','Integraciones y automatizaciones que reducen tareas repetitivas y mejoran la productividad.'],visit:'Visitar proyecto',request:'Solicitar información',benefits:['Diseño adaptable a móviles','Soluciones según tus necesidades','Comunicación directa durante el proyecto']},
 en:{nav:['Home','About','Projects','Services','Blog','Contact'],tag:'Technology and innovation',title:'We turn ideas into digital solutions.',intro:'We are a digital project founded by Isaías Díaz. We build websites, applications and AI-powered automations for individuals and businesses.',projects:'Featured projects',projectsDesc:'Tools and platforms I have developed.',services:'Digital services',servicesDesc:'We create practical solutions for people, brands and businesses.',about:'About me',aboutText:'I enjoy creating useful tools and exploring new possibilities with technology.',blog:'Blog',blogText:'Articles about technology, artificial intelligence and digital development are coming soon.',contact:'Let’s talk about your project',contactText:'Have an idea or a collaboration proposal? Get in touch.',cta:'View projects',contactCta:'Contact',theme:'Toggle theme',cards:['Web development','Digital applications','AI automation'],descs:['Professional, mobile-friendly business websites with performance and technical SEO in mind.','Custom tools to simplify business processes and everyday tasks.','Integrations and automations that reduce repetitive work and improve productivity.'],visit:'Visit project',request:'Request information',benefits:['Mobile-friendly design','Solutions tailored to your needs','Direct communication throughout the project']},
 pt:{nav:['Início','Sobre mim','Projetos','Serviços','Blog','Contato'],tag:'Tecnologia e inovação',title:'Transformamos ideias em soluções digitais.',intro:'Somos um projeto digital criado por Isaías Díaz. Desenvolvemos sites, aplicativos e automações com inteligência artificial para pessoas e empresas.',projects:'Projetos em destaque',projectsDesc:'Ferramentas e plataformas que desenvolvi.',services:'Serviços digitais',servicesDesc:'Criamos soluções práticas para pessoas, marcas e empresas.',about:'Sobre mim',aboutText:'Gosto de criar ferramentas úteis e explorar novas possibilidades com tecnologia.',blog:'Blog',blogText:'Em breve, artigos sobre tecnologia, inteligência artificial e desenvolvimento digital.',contact:'Vamos conversar sobre seu projeto',contactText:'Tem uma ideia ou proposta de colaboração? Entre em contato.',cta:'Ver projetos',contactCta:'Contato',theme:'Alternar tema',cards:['Desenvolvimento web','Aplicativos digitais','Automação com IA'],descs:['Sites profissionais e responsivos, com foco em desempenho e SEO técnico.','Ferramentas personalizadas para simplificar processos e tarefas.','Integrações e automações que reduzem o trabalho repetitivo e melhoram a produtividade.'],visit:'Visitar projeto',request:'Solicitar informações',benefits:['Design adaptado para dispositivos móveis','Soluções para suas necessidades','Comunicação direta durante o projeto']}
} as const;
type Lang=keyof typeof data;
const seo={es:{title:'Desarrollo web y automatización con IA | Isaías Díaz',description:'Diseño y desarrollo de sitios web, aplicaciones digitales y automatizaciones con inteligencia artificial. Conoce mis proyectos y solicita una propuesta.'},en:{title:'Web Development & AI Automation | Isaías Díaz',description:'Web development, digital applications and AI automation for businesses and entrepreneurs. Explore my projects and get in touch.'},pt:{title:'Desenvolvimento Web e Automação com IA | Isaías Díaz',description:'Desenvolvimento de sites, aplicativos digitais e automação com inteligência artificial. Conheça meus projetos e entre em contato.'}} as const;
export async function generateMetadata({params}:{params:Promise<{lang:string}>}):Promise<Metadata>{const {lang}=await params;const locale:Lang=lang==='en'||lang==='pt'?lang:'es';const {title,description}=seo[locale];const url='https://isaiasdiaz.com/'+locale+'/';return {title:{absolute:title},description,alternates:{canonical:url,languages:{'es':'https://isaiasdiaz.com/es/','en':'https://isaiasdiaz.com/en/','pt':'https://isaiasdiaz.com/pt/','x-default':'https://isaiasdiaz.com/'}},openGraph:{title,description,url,locale:locale==='es'?'es_SV':locale==='en'?'en_US':'pt_BR',type:'website'},twitter:{card:'summary',title,description}}}

export function generateStaticParams(){return [{lang:'es'},{lang:'en'},{lang:'pt'}]}
export default async function Page({params}:{params:Promise<{lang:string}>}){
 const {lang}=await params;const locale:Lang=lang==='en'||lang==='pt'?lang:'es';const t=data[locale];
 return <><header className="top wrap"><Link className="brand" href={`/${locale}/`}>Isaías Díaz</Link><nav className="nav" aria-label="Main navigation">{t.nav.map((x,i)=><a key={x} href={`#${['home','about','projects','services','blog','contact'][i]}`}>{x}</a>)}</nav><div className="langs">{(['es','en','pt'] as const).map(x=><Link key={x} href={`/${x}/`} aria-current={locale===x?'page':undefined}>{x.toUpperCase()}</Link>)}<ThemeToggle label={t.theme}/></div></header>
 <main><section className="hero wrap hero-layout" id="home"><div className="hero-copy"><div className="eyebrow"><span className="status-dot"/> {t.tag}</div><h1>{t.title}</h1><p>{t.intro}</p><div className="actions"><a className="btn primary" href="#projects">{t.cta} ↗</a><a className="btn" href="#services">{t.services}</a></div><div className="hero-chips"><span>Next.js</span><span>AI & Automation</span><span>Cloudflare</span></div></div><div className="hero-art" aria-hidden="true"><div className="art-orbit orbit-one"/><div className="art-orbit orbit-two"/><div className="art-core"><div className="core-inner"/></div><div className="art-label label-top">{"</>"} Digital</div><div className="art-label label-bottom">✦ Innovation</div></div></section>
 <section className="section wrap" id="about"><h2>{t.about}</h2><p className="lead">{t.aboutText}</p></section>
 <section className="section wrap" id="projects"><h2>{t.projects}</h2><p className="lead">{t.projectsDesc}</p><div className="grid"><article className="card project-card"><div className="project-icon">◈</div><h3>UtiliToolsPro</h3><p>Online tools and digital utilities.</p><a href="https://utilitoolspro.com/" target="_blank" rel="noopener noreferrer">{t.visit} ↗</a></article><article className="card project-card"><div className="project-icon">♫</div><h3>Radio Juvenil</h3><p>Radio digital y música urbana cristiana.</p><a href="https://radiojuvenil24h.blogspot.com/" target="_blank" rel="noopener noreferrer">{t.visit} ↗</a></article><article className="card project-card"><div className="project-icon">▣</div><h3>UtiliZip</h3><p>Desktop file compression utility. </p></article></div></section>
 <section className="section wrap" id="services"><h2>{t.services}</h2><p className="lead">{t.servicesDesc}</p><div className="grid">{t.cards.map((c,i)=><article className="card" key={c}><h3>{c}</h3><p>{t.descs[i]}</p><a href="#contact">{t.request} ↗</a></article>)}</div></section>
 <section className="section wrap" id="blog"><h2>{t.blog}</h2><p className="lead">{t.blogText}</p></section>
 <section className="section wrap" id="contact"><h2>{t.contact}</h2><p className="lead">{t.contactText}</p><ContactForm lang={locale}/></section></main><footer className="footer"><div className="wrap">© {new Date().getFullYear()} Isaías Díaz · {t.tag}</div></footer></>;
}
