import type { Metadata } from 'next';
import Link from 'next/link';

const catalog={
 'finanzas-personales-para-principiantes':{
 title:'Finanzas personales para principiantes',
 subtitle:'Guía práctica para aprender a manejar tu dinero de forma simple, clara y efectiva',
 cover:'/portada-finanzas-personales.png',
 amazon:'https://www.amazon.com/dp/B0H4CV13VV',
 intro:'Finanzas Personales para Principiantes es una guía práctica diseñada para ayudarte a ordenar tu dinero, crear un presupuesto simple, ahorrar aunque empieces con poco y evitar errores financieros comunes.',
 topics:['Entender tus ingresos y gastos','Hacer un presupuesto fácil de seguir','Crear el hábito del ahorro','Salir del desorden financiero','Evitar deudas peligrosas','Construir estabilidad financiera paso a paso'],
 conclusion:'Si sientes que tu dinero desaparece rápido, que no sabes en qué se va o que necesitas empezar desde cero, esta guía te ayudará a tomar el control de tus finanzas de manera clara, sencilla y práctica.',
 audience:'Ideal para principiantes que quieren mejorar su relación con el dinero y comenzar a construir un futuro financiero más ordenado.'
 },
 'como-ahorrar-dinero-aunque-ganes-poco':{
 title:'Cómo ahorrar dinero aunque ganes poco',
 subtitle:'Un método práctico para organizar tus ingresos, reducir gastos y construir ahorros desde cero',
 cover:'/portada-como-ahorrar.png',
 amazon:'https://a.co/d/0fMt73Ae',
 intro:'¿Sientes que ahorrar es imposible porque ganas poco o porque el dinero desaparece antes de terminar el mes? Este libro es una guía práctica para organizar mejor tus ingresos, reducir gastos innecesarios y comenzar a construir ahorros desde cero, sin fórmulas complicadas ni promesas irreales. Está pensado para personas que buscan estrategias sencillas, realistas y fáciles de aplicar.',
 topics:['Identificar en qué se va realmente tu dinero','Crear un presupuesto adaptado a tus ingresos','Reducir gastos sin sentir que dejas de vivir','Controlar las compras impulsivas','Ahorrar en supermercado, transporte y servicios','Organizar tus deudas','Construir un fondo de emergencia','Ahorrar aunque tus ingresos sean variables','Aprovechar bonos e ingresos extraordinarios','Aumentar tu capacidad de ahorro','Crear metas financieras realistas','Desarrollar hábitos sostenibles a largo plazo'],
 extras:'Incluye retos de ahorro, ejemplos sencillos, ejercicios prácticos, un plan financiero de 12 meses y recursos digitales que puedes utilizar desde tu teléfono, computadora o aplicación de notas.',
 conclusion:'No necesitas ganar mucho para comenzar. Puedes empezar con lo que tienes hoy, aunque tu primer ahorro sea de $5, $10 o $20.',
 audience:'Si quieres dejar de sentir que el dinero se te escapa de las manos y avanzar hacia una mayor tranquilidad económica, este libro puede ser tu punto de partida.'
 }
} as const;
type Slug=keyof typeof catalog;
const slugs=Object.keys(catalog) as Slug[];

const langs=['es','en','pt'] as const;
const ui={
 es:{back:'Volver a todos los libros',series:'Colección Dinero Inteligente',learn:'En este libro aprenderás a',extras:'Recursos y herramientas',amazon:'Ver libro en Amazon',shop:'Ver tienda de libros PDF',note:'La venta directa de PDF está en preparación. Puedes consultar la edición disponible en Amazon.',language:'Libro en español',author:'Autor: Isaías Díaz',related:'También te puede interesar',details:'Conoce el otro libro',nav:'Cambiar idioma',collection:'Ver colección completa'},
 en:{back:'Back to all books',series:'Dinero Inteligente Collection',learn:'What you will learn',extras:'Resources and tools',amazon:'View on Amazon',shop:'Explore PDF bookstore',note:'Direct PDF sales are being prepared. The available edition can be viewed on Amazon.',language:'Book written in Spanish',author:'Author: Isaías Díaz',related:'You may also like',details:'Discover the other book',nav:'Change language',collection:'View the full collection'},
 pt:{back:'Voltar aos livros',series:'Coleção Dinero Inteligente',learn:'O que você vai aprender',extras:'Recursos e ferramentas',amazon:'Ver na Amazon',shop:'Conhecer a loja de PDFs',note:'A venda direta de PDFs está em preparação. A edição disponível pode ser consultada na Amazon.',language:'Livro em espanhol',author:'Autor: Isaías Díaz',related:'Você também pode gostar',details:'Conheça o outro livro',nav:'Mudar idioma',collection:'Ver coleção completa'}
} as const;
const translatedContent={
 en:{
 'finanzas-personales-para-principiantes':{title:'Personal Finance for Beginners',subtitle:'A practical guide to managing money simply, clearly and effectively',intro:'This practical Spanish-language guide helps you organize your finances, build a simple budget, save even when starting small, and avoid common financial mistakes.',topics:['Understand your income and expenses','Create an easy-to-follow budget','Build a saving habit','Get your finances organized','Avoid dangerous debt','Build financial stability step by step'],conclusion:'If your money seems to disappear quickly or you are starting from scratch, this guide offers clear, practical steps to take control.',audience:'Ideal for beginners who want a healthier relationship with money and a more organized financial future.'},
 'como-ahorrar-dinero-aunque-ganes-poco':{title:'How to Save Money Even on a Low Income',subtitle:'A practical method to organize income, cut expenses and start saving from zero',intro:'Does saving seem impossible because your income is limited or money runs out before month-end? This Spanish-language guide offers simple, realistic ways to organize income, reduce unnecessary expenses and begin saving.',topics:['See where your money really goes','Build a budget for your income','Reduce expenses without giving up everything','Control impulse purchases','Save on groceries, transport and bills','Organize debt','Build an emergency fund','Save with variable income','Make better use of bonuses and extra income','Increase your ability to save','Set realistic financial goals','Build long-term habits'],extras:'Includes savings challenges, practical exercises, simple examples, a 12-month financial plan and digital resources for your phone or computer.',conclusion:'You do not need a high income to begin. Start with what you have today, even if your first savings are $5, $10 or $20.',audience:'For readers seeking more control over their money and greater financial peace of mind.'}
 },
 pt:{
 'finanzas-personales-para-principiantes':{title:'Finanças Pessoais para Iniciantes',subtitle:'Um guia prático para administrar seu dinheiro de forma simples, clara e eficaz',intro:'Este guia prático, escrito em espanhol, ajuda você a organizar suas finanças, criar um orçamento simples, poupar mesmo começando com pouco e evitar erros financeiros comuns.',topics:['Entender receitas e despesas','Criar um orçamento fácil de seguir','Desenvolver o hábito de poupar','Organizar as finanças','Evitar dívidas perigosas','Construir estabilidade financeira passo a passo'],conclusion:'Se o dinheiro desaparece rapidamente ou você está começando do zero, este guia oferece passos claros e práticos para assumir o controle.',audience:'Ideal para iniciantes que desejam melhorar sua relação com o dinheiro e construir um futuro financeiro mais organizado.'},
 'como-ahorrar-dinero-aunque-ganes-poco':{title:'Como Economizar Dinheiro Mesmo Ganhando Pouco',subtitle:'Um método prático para organizar receitas, reduzir despesas e começar a poupar do zero',intro:'Parece impossível economizar porque a renda é baixa ou o dinheiro acaba antes do fim do mês? Este guia, escrito em espanhol, apresenta estratégias simples e realistas para organizar receitas, reduzir gastos desnecessários e começar a poupar.',topics:['Identificar para onde vai o dinheiro','Criar um orçamento adaptado à renda','Reduzir despesas sem abrir mão de tudo','Controlar compras por impulso','Economizar em supermercado, transporte e serviços','Organizar dívidas','Criar uma reserva de emergência','Poupar com renda variável','Aproveitar bônus e renda extra','Aumentar a capacidade de poupar','Definir metas financeiras realistas','Criar hábitos duradouros'],extras:'Inclui desafios de poupança, exercícios práticos, exemplos simples, um plano financeiro de 12 meses e recursos digitais para celular ou computador.',conclusion:'Não é necessário ganhar muito para começar. Comece com o que tem hoje, mesmo que sejam apenas US$ 5, US$ 10 ou US$ 20.',audience:'Para quem busca mais controle sobre o dinheiro e maior tranquilidade financeira.'}
 }
} as const;
function getBook(locale:'es'|'en'|'pt',slug:Slug){return locale==='es'?catalog[slug]:translatedContent[locale][slug];}

export function generateStaticParams(){return langs.flatMap(lang=>(Object.keys(catalog) as Slug[]).map(slug=>({lang,slug})));}
export async function generateMetadata({params}:{params:Promise<{lang:string;slug:string}>}):Promise<Metadata>{
 const {lang,slug}=await params;const book=catalog[slug as Slug];if(!book)return {title:'Libro no encontrado'};
 const locale=lang==='en'||lang==='pt'?lang:'es';const localized=getBook(locale,slug as Slug);const root='https://isaiasdiaz.com';return {title:`${localized.title} | Isaías Díaz`,description:localized.subtitle,alternates:{canonical:`${root}/${lang}/libros/${slug}/`,languages:{es:`${root}/es/libros/${slug}/`,en:`${root}/en/libros/${slug}/`,pt:`${root}/pt/libros/${slug}/`}},openGraph:{title:localized.title,description:localized.subtitle,url:`${root}/${locale}/libros/${slug}/`,type:'book',images:[{url:book.cover,alt:book.title}]},twitter:{card:'summary_large_image',title:localized.title,description:localized.subtitle,images:[book.cover]}};
}
export default async function BookDetail({params}:{params:Promise<{lang:string;slug:string}>}){
 const {lang,slug}=await params;const locale=lang==='en'||lang==='pt'?lang:'es';const book=catalog[slug as Slug];const t=ui[locale];const localized=book?getBook(locale,slug as Slug):null;const relatedSlug=slugs.find(s=>s!==slug);
 if(!book)return <main className="wrap section"><h1>Libro no encontrado</h1><Link href={`/${locale}/libros/`}>{t.back}</Link></main>;
 return <><header className="top wrap"><Link className="books-header-logo" href="/prueba/" aria-label="Isaías Díaz — Soluciones Digitales"><img src="/logo-id.png" alt="Isaías Díaz — Soluciones Digitales" /></Link><nav className="nav"><Link href={`/${locale}/libros/`}>{t.back}</Link></nav></header>
 <main className="wrap"><section className="section book-detail"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({"@context":"https://schema.org","@type":"Book",name:book.title,author:{"@type":"Person",name:"Isaías Díaz"},inLanguage:"es",image:`https://isaiasdiaz.com${book.cover}`,description:book.subtitle,url:`https://isaiasdiaz.com/${locale}/libros/${slug}/`,sameAs:book.amazon}).replace(/</g,"\\u003c")}} /><Link className="book-detail-back" href={`/${locale}/libros/`}>← {t.back}</Link><div className="book-detail-grid"><div className="book-detail-art"><img src={book.cover} alt={`Portada de ${book.title}`}/></div><div className="book-detail-content"><nav className="book-detail-languages" aria-label={t.nav}>{langs.map(l=><Link key={l} href={`/${l}/libros/${slug}/`} aria-current={locale===l?"page":undefined}>{l.toUpperCase()}</Link>)}</nav><div className="eyebrow">{t.series}</div><h1>{localized?.title}</h1><p className="book-detail-subtitle">{localized?.subtitle}</p><p className="books-author">{t.author} · {t.language}</p><p>{localized?.intro}</p><h2>{t.learn}</h2><ul>{localized?.topics.map(topic=><li key={topic}>{topic}</li>)}</ul>{'extras' in book&&<><h2>{t.extras}</h2><p>{'extras' in (localized || {}) ? (localized as {extras:string}).extras : ''}</p></>}<p>{localized?.conclusion}</p><p>{localized?.audience}</p><div className="books-actions"><a className="btn primary" href={book.amazon} target="_blank" rel="noopener noreferrer" style={{color:'white'}}>{t.amazon} ↗</a><Link className="books-shop-link" href="/prueba/tienda/">{t.shop} ↗</Link></div><p className="books-note">{t.note}</p></div></div>{relatedSlug&&<aside className="book-detail-related"><h2>{t.related}</h2><Link href={`/${locale}/libros/${relatedSlug}/`}><img src={catalog[relatedSlug].cover} alt={catalog[relatedSlug].title} loading="lazy"/><span><strong>{getBook(locale,relatedSlug).title}</strong><small>{t.details} →</small></span></Link></aside>}<p className="book-detail-all"><Link href={`/${locale}/libros/`}>← {t.collection}</Link></p></section></main><footer className="footer"><div className="wrap">© {new Date().getFullYear()} Isaías Díaz</div></footer></>;
}
