import type { Metadata } from 'next';
import Link from 'next/link';
const services={
 es:{heading:'Soluciones digitales para tus proyectos',intro:'Desarrollamos herramientas prácticas para mejorar tu presencia en Internet y simplificar procesos.',home:'Inicio',contact:'Solicitar información',items:[{slug:'desarrollo-web',title:'Desarrollo web',intro:'Sitios web profesionales, rápidos y adaptados a móviles.',features:['Diseño responsive y accesible','Optimización de rendimiento y SEO técnico','Integración de formularios y funcionalidades útiles']},{slug:'aplicaciones-digitales',title:'Aplicaciones digitales',intro:'Herramientas y aplicaciones pensadas para necesidades concretas.',features:['Análisis de necesidades y funcionalidades','Interfaces claras y fáciles de utilizar','Mejoras y evolución del producto']},{slug:'automatizacion-ia',title:'Automatización con IA',intro:'Reducimos tareas repetitivas mediante integraciones y flujos automatizados.',features:['Identificación de procesos repetitivos','Automatización de tareas y datos','Integración responsable de herramientas de IA']}]},
 en:{heading:'Digital solutions for your projects',intro:'We build practical tools to strengthen your online presence and simplify processes.',home:'Home',contact:'Request information',items:[{slug:'desarrollo-web',title:'Web development',intro:'Professional, fast and mobile-friendly websites.',features:['Responsive, accessible design','Performance and technical SEO','Forms and useful integrations']},{slug:'aplicaciones-digitales',title:'Digital applications',intro:'Tools and apps tailored to real needs.',features:['Requirements and feature planning','Clear, easy-to-use interfaces','Product improvements and iteration']},{slug:'automatizacion-ia',title:'AI automation',intro:'Reduce repetitive tasks with integrations and automated workflows.',features:['Identify repetitive processes','Automate tasks and data flows','Responsible AI tool integration']}]},
 pt:{heading:'Soluções digitais para seus projetos',intro:'Criamos ferramentas práticas para fortalecer sua presença online e simplificar processos.',home:'Início',contact:'Solicitar informações',items:[{slug:'desarrollo-web',title:'Desenvolvimento web',intro:'Sites profissionais, rápidos e adaptados a dispositivos móveis.',features:['Design responsivo e acessível','Desempenho e SEO técnico','Formulários e integrações úteis']},{slug:'aplicaciones-digitales',title:'Aplicativos digitais',intro:'Ferramentas e aplicativos para necessidades reais.',features:['Planejamento de requisitos e funcionalidades','Interfaces claras e fáceis de usar','Melhorias contínuas do produto']},{slug:'automatizacion-ia',title:'Automação com IA',intro:'Reduza tarefas repetitivas com integrações e fluxos automatizados.',features:['Identificação de processos repetitivos','Automação de tarefas e dados','Integração responsável de ferramentas de IA']}]}
} as const;
type Lang=keyof typeof services;
export function generateStaticParams(){return [{lang:'es'},{lang:'en'},{lang:'pt'}]}
export async function generateMetadata({params}:{params:Promise<{lang:string}>}):Promise<Metadata>{const {lang}=await params;const locale:Lang=lang==='en'||lang==='pt'?lang:'es';const t=services[locale];return {title:t.heading,description:t.intro,robots:{index:false,follow:false},alternates:{canonical:`https://isaiasdiaz.com/${locale}/servicios/`,languages:{es:'https://isaiasdiaz.com/es/servicios/',en:'https://isaiasdiaz.com/en/servicios/',pt:'https://isaiasdiaz.com/pt/servicios/'}}}}
export default async function Services({params}:{params:Promise<{lang:string}>}){const {lang}=await params;const locale:Lang=lang==='en'||lang==='pt'?lang:'es';const t=services[locale];return <><header className="top wrap"><Link className="brand" href={`/${locale}/`}>Isaías Díaz</Link><nav className="nav"><Link href={`/${locale}/`}>{t.home}</Link></nav><div className="langs">{(['es','en','pt'] as const).map(l=><Link key={l} href={`/${l}/servicios/`} aria-current={locale===l?'page':undefined}>{l.toUpperCase()}</Link>)}</div></header><main className="wrap"><section className="section"><div className="eyebrow">Isaías Díaz</div><h1>{t.heading}</h1><p className="lead">{t.intro}</p><div className="grid">{t.items.map(item=><article className="card" key={item.slug}><h2 style={{fontSize:'1.35rem'}}>{item.title}</h2><p>{item.intro}</p><ul>{item.features.map(f=><li key={f}>{f}</li>)}</ul><a href="mailto:contacto@isaiasdiaz.com?subject=Consulta%20sobre%20servicios">{t.contact} ↗</a></article>)}</div></section></main><footer className="footer"><div className="wrap">© {new Date().getFullYear()} Isaías Díaz</div></footer></>}
