import type { Metadata } from 'next';
import Link from 'next/link';
const translations={
 es:{title:'Libros de Isaías Díaz',description:'Descubre los libros publicados por Isaías Díaz y encuéntralos en Amazon.',heading:'Libros y publicaciones',intro:'Un espacio para compartir mis libros sobre finanzas personales, aprendizaje y crecimiento. Aquí encontrarás las publicaciones disponibles en Amazon.',book:'Finanzas personales para principiantes',detail:'Guía práctica para aprender a manejar tu dinero de forma simple, clara y efectiva. Aprende a organizar ingresos y gastos, elaborar un presupuesto, ahorrar y evitar errores financieros comunes.',buy:'Ver libro en Amazon',back:'Volver al inicio',author:'Autor: Isaías Díaz',second:'Cómo ahorrar dinero aunque ganes poco',secondDetail:'Un método práctico para organizar tus ingresos, reducir gastos y construir ahorros desde cero.',series:'Colección Dinero Inteligente',seriesIntro:'Dos guías complementarias para tomar el control de tu dinero, desarrollar hábitos de ahorro y construir estabilidad financiera.',topics:'Qué aprenderás',topics1:['Organizar ingresos y gastos','Crear un presupuesto realista','Mejorar tus decisiones financieras','Empezar a construir estabilidad'],topics2:['Ahorrar incluso con ingresos limitados','Identificar gastos que puedes reducir','Crear un plan de ahorro alcanzable','Desarrollar hábitos sostenibles'],format:'Idioma: español · Edición digital disponible en Amazon',shop:'Conocer la tienda de PDF',shopNote:'La compra directa de PDF está en preparación.',more:'Conocer más sobre el libro'},
 en:{title:'Books by Isaías Díaz',description:'Explore books by Isaías Díaz available on Amazon.',heading:'Books and publications',intro:'A place to share my books about personal finance, learning and growth. Find my publications on Amazon.',book:'Personal Finance for Beginners',detail:'A practical Spanish-language guide to organizing your finances, creating a budget, saving money and avoiding common financial mistakes.',buy:'View on Amazon',back:'Back to home',author:'Author: Isaías Díaz',second:'Cómo ahorrar dinero aunque ganes poco',secondDetail:'A Spanish-language practical method to organize income, reduce expenses and build savings from scratch.',series:'Dinero Inteligente Collection',seriesIntro:'Two complementary Spanish-language guides to budgeting, saving and building healthier financial habits.',topics:'What you will learn',topics1:['Track income and expenses','Create a realistic budget','Make better financial decisions','Build financial stability'],topics2:['Save on a limited income','Find expenses to reduce','Set achievable savings goals','Develop lasting habits'],format:'Language: Spanish · Digital edition on Amazon',shop:'Explore the PDF store',shopNote:'Direct PDF purchases are being prepared.',more:'Learn more about this book'},
 pt:{title:'Livros de Isaías Díaz',description:'Conheça os livros de Isaías Díaz disponíveis na Amazon.',heading:'Livros e publicações',intro:'Um espaço para compartilhar meus livros sobre finanças pessoais, aprendizado e crescimento. Encontre minhas publicações na Amazon.',book:'Finanças pessoais para iniciantes',detail:'Guia prática em espanhol para organizar suas finanças, criar um orçamento, economizar e evitar erros financeiros comuns.',buy:'Ver na Amazon',back:'Voltar ao início',author:'Autor: Isaías Díaz',second:'Cómo ahorrar dinero aunque ganes poco',secondDetail:'Um método prático em espanhol para organizar rendimentos, reduzir despesas e começar a poupar.',series:'Coleção Dinero Inteligente',seriesIntro:'Dois guias complementares em espanhol sobre orçamento, poupança e hábitos financeiros.',topics:'O que você vai aprender',topics1:['Organizar receitas e despesas','Criar um orçamento realista','Melhorar decisões financeiras','Construir estabilidade'],topics2:['Poupar com renda limitada','Identificar gastos a reduzir','Criar metas alcançáveis','Desenvolver hábitos duradouros'],format:'Idioma: espanhol · Edição digital na Amazon',shop:'Conhecer a loja de PDFs',shopNote:'A compra direta de PDFs está em preparação.',more:'Saiba mais sobre o livro'}
} as const;
type Lang=keyof typeof translations;
export function generateStaticParams(){return [{lang:'es'},{lang:'en'},{lang:'pt'}]}
export async function generateMetadata({params}:{params:Promise<{lang:string}>}):Promise<Metadata>{
 const {lang}=await params;const locale:Lang=lang==='en'||lang==='pt'?lang:'es';const t=translations[locale];
 const root='https://isaiasdiaz.com';return {title:t.title,description:t.description,alternates:{canonical:`${root}/${locale}/libros/`,languages:{es:`${root}/es/libros/`,en:`${root}/en/libros/`,pt:`${root}/pt/libros/`}},openGraph:{title:t.title,description:t.description,url:`${root}/${locale}/libros/`,type:'website'}};
}
export default async function Books({params}:{params:Promise<{lang:string}>}){
 const {lang}=await params;const locale:Lang=lang==='en'||lang==='pt'?lang:'es';const t=translations[locale];
 const books=[{title:t.book,detail:t.detail,cover:'/portada-finanzas-personales.png',topics:t.topics1,slug:'finanzas-personales-para-principiantes',amazon:'https://www.amazon.com/dp/B0H4CV13VV'},{title:t.second,detail:t.secondDetail,cover:'/portada-como-ahorrar.png',topics:t.topics2,slug:'como-ahorrar-dinero-aunque-ganes-poco',amazon:'https://a.co/d/0fMt73Ae'}];
 return <><header className="top wrap"><Link className="books-header-logo" href="/prueba/" aria-label="Isaías Díaz — Soluciones Digitales"><img src="/logo-id.png" alt="Isaías Díaz — Soluciones Digitales" /></Link><nav className="nav"><Link href={`/${locale}/`}>{t.back}</Link></nav><div className="langs">{(['es','en','pt'] as const).map(x=><Link key={x} href={`/${x}/libros/`} aria-current={locale===x?'page':undefined}>{x.toUpperCase()}</Link>)}</div></header><main className="wrap"><section className="section books-page"><div className="eyebrow">{t.series}</div><h1>{t.heading}</h1><p className="lead">{t.intro}</p><p className="books-series-intro">{t.seriesIntro}</p><div className="books-catalog">{books.map((book,i)=><article className="books-item" key={book.title}><div className="books-cover-panel"><img src={book.cover} alt={`Portada: ${book.title}`} loading={i===0?'eager':'lazy'}/></div><div className="books-item-info"><span className="books-series-label">{t.series} · {String(i+1).padStart(2,'0')}</span><h2>{book.title}</h2><p className="books-author">{t.author}</p><p>{book.detail}</p><h3>{t.topics}</h3><ul>{book.topics.map(topic=><li key={topic}>{topic}</li>)}</ul><p className="books-format">{t.format}</p><div className="books-actions"><Link className="btn primary" href={`/${locale}/libros/${book.slug}/`} style={{color:"white"}}>{t.more} →</Link><a className="btn primary" href={book.amazon} target="_blank" rel="noopener noreferrer" style={{color:'white'}}>{t.buy} ↗</a><Link className="books-shop-link" href="/prueba/tienda/">{t.shop} ↗</Link></div><small className="books-note">{t.shopNote}</small></div></article>)}</div></section></main><footer className="footer"><div className="wrap">© {new Date().getFullYear()} Isaías Díaz</div></footer></>;
}